### ISSUE TITLE
Relay command

### ISSUE THREAD

**Issue by Akstef** [roleoroleo/4-noks_ha_integration#7]
Hi

Is there any way to command the integrated relay from home assistant?

**Comment by roleoroleo** [comment]
It's not implemented at the moment.

**Comment by roleoroleo** [comment]
If you are able to sniff the commands between the app and the device, I could try to add them to this integration.

**Comment by Akstef** [comment]
Hi.
Thank you for your assistance.
To read the data we need to send @dat on a ssh terminal connected to the elios 4 you. I can find the @dat command in the integration python file but I am unable to modify the code.
To close the built in relay we have to send the command @rel 0 1.
To open the relay the command @rel 0 0

**Comment by Akstef** [comment]
I find a way to command the built in relay.
I have added these lines in configuration.yaml

switch:
  - platform: telnet
    switches:
      water_heater:
        resource: **IP adress of the elios 4 you**
        port: 5001
        command_on: "@rel 0 1"
        command_off: "@rel 0 0"
        name: water heater

This will add a switch in home assistant and you can control the built in relay. By default it will take 1 minute to indicate the new relay status. If you want to lower the refresh time you have to edit the file sensor.py located in config/custom_components/4_noks and on the line 48 you can change the refresh interval (update_interval=timedelta(seconds=**10**),

**Comment by roleoroleo** [comment]
I will check the code.
Thanks.

**Comment by roleoroleo** [comment]
What is the response of the command?
Does the line ";Relay state;0;;" change when you send the command?

Sorry but I don't own the 4-noks module anymore.

**Comment by Akstef** [comment]
Yes, the relay state change after 1 minute (by default). The update time can be changed. See my previous post.
I have tested first on a computer connected via putty in telnet configuration. When you send a command @rel you receive some repply message but I have not done a capture. The repply message is not interesting for my application. I need only the relay properly commanded which is the case.

**Comment by roleoroleo** [comment]
Please, try this new version:
[4_noks_0.0.4.tar.gz](https://github.com/roleoroleo/4-noks_ha_integration/files/12547984/4_noks_0.0.4.tar.gz)

**Comment by Akstef** [comment]
I will test it this week end but with the configuration given earlier it is working fine. I will let you know next week.

**Comment by Akstef** [comment]
@roleoroleo 
I have tested your software. I can control the built in relay but you have changed the file sensor.py and I am not able to change the update interval. I use the data from my elios 4 you to have the real time energy values so I need an update rate of 10s.
Is it possible to add an option so we can choose the update interval from home assistant without editing the file?

**Comment by roleoroleo** [comment]
Try this:
[4_noks_0.0.5.tar.gz](https://github.com/roleoroleo/4-noks_ha_integration/files/12676215/4_noks_0.0.5.tar.gz)

I added a new option when you add the integration.
So, remove the device and add it again.

Let me know if it works.

**Comment by Daneltones8** [comment]
Hi,
Thank you very much for this integration.
i enabled only bought energy, bought power, relay state and relay command.
it works perfectly just after some hours of work seems device doesn't answer anymore.
i post here error message just to understand if there is some bug in code or my Elios device after some time lose packet and fail to response. (i disabled from elios app to send data to cloud for not to occupy resource on it).
(update time i set on 20 seconds)

Thank you boss!

************************************************************************************************
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 524, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/4_noks/sensor.py", line 82, in native_value
    return self.coordinator.data[self._basename]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'Bought Power'

**Comment by roleoroleo** [comment]
It's an unhandled exception.
But I don't understand why it happens.

In sensor.py, replace the native_value function with this one and check if it works:
```
    @property
    def native_value(self):
        """Return the value of the sensor."""
        if self.coordinator.data is not None:
            try:
                return self.coordinator.data[self._basename]
            except KeyError:
                _LOGGER.error("Unable to read value for sensor %s", self._basename)
```

**Comment by Daneltones8** [comment]
Thank you very much this fixed the exception!
the integration works perfect.

Result for managed exception:
Unable to read value for sensor Bought Power
Unable to read value for sensor Bought Energy
Unable to read value for sensor Relay state

My device have a problem that after some hours crash wifi module and remain offline but this is hardware problem.

Thanks for your help boss!
